steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Deploying Airflow DAGs to GCS bucket..."
        gsutil -m rsync -r dags gs://us-central1-airflow-demo-838b4df0-bucket/dags

# Add this options section
options:
  logging: CLOUD_LOGGING_ONLY

timeout: '900s'